# Generated by Django 3.2.6 on 2021-08-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.PositiveIntegerField(verbose_name='Profile')),
                ('text', models.TextField(verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Collect date')),
            ],
            options={
                'verbose_name': 'Message_url',
                'verbose_name_plural': 'Message_url',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='Account ID')),
                ('name', models.TextField(default=None, verbose_name='Name')),
                ('first_name', models.TextField(default=None, verbose_name='First Name')),
                ('l_name', models.TextField(default=None, verbose_name='Last Name')),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
    ]
