# Generated by Django 3.2.6 on 2021-09-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='external_id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name='Account ID'),
        ),
    ]
