# Generated by Django 3.2.6 on 2021-08-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0002_auto_20210830_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Name'),
        ),
    ]
