# Generated by Django 3.2.6 on 2021-08-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0002_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Message'},
        ),
    ]
