# Generated by Django 3.2.6 on 2021-09-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_alter_profile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_url',
            name='file_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Video name'),
        ),
    ]
