# Generated by Django 3.2.6 on 2021-08-30 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0004_auto_20210830_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Collect date'),
            preserve_default=False,
        ),
    ]
