# Generated by Django 3.2.6 on 2021-08-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0004_alter_profile_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(default=None, verbose_name='Name'),
        ),
    ]
